[package]
name = "usart"
version = "0.1.0"
authors = ["jamil"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stmlib = {path = "stmlib"}

[dependencies.heapless]
default-features = false
version = "0.3.7"